version: '3.1'
services:
  redis:
    image: redis
  api:
    container_name: juripredis_annuaire_api
    build:
      context: .
      dockerfile: docker/test/Dockerfile
    environment:
      DATA_DIR: $DATA_DIR
      CELERY_RESULT_BACKEND: redis://redis:6379
      CELERY_BROKER_URL: redis://redis:6379
    ports:
      - "5001:5000"
    volumes:
      - .:/app
    links:
      - redis
      - worker
  worker:
    container_name: juripredis_annuaire_worker
    command: python -m manage celery --loglevel=debug
    environment:
      DATA_DIR: $DATA_DIR
      CELERY_RESULT_BACKEND: redis://redis:6379
      CELERY_BROKER_URL: redis://redis:6379
    build:
      context: .
      dockerfile: docker/annuaire/Dockerfile
    depends_on:
      - redis
    links:
      - redis
